name: Actualización de Base de Datos

on:
  schedule:
    # 13:00 UTC es 10:00 AM Argentina (UTC-3)
    - cron: '0 13 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Descargar Repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar Librerías
        run: |
          pip install requests pandas cloudscraper

      - name: Ejecutar Actualización
        run: python api.py

      - name: Guardar Cambios en GitHub
        id: commit_step
        run: |
          git config --global user.name "Bot de Actualización"
          git config --global user.email "actions@github.com"
          git add LIGA_ARG_2025.db update_log.txt
          
          if git diff --staged --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No hay cambios para subir."
          else
            git commit -m "Auto-update: DB y Logs $(date +'%Y-%m-%d')"
            git push
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Disparar Deploy en Render
        if: steps.commit_step.outputs.changes == 'true'
        run: |
          curl -s ${{ secrets.RENDER_DEPLOY_HOOK }} > /dev/null